config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'projects#index'
  get 'projects/new', to: 'projects#new'
  post 'projects', to: 'projects#create'
  delete 'projects/:id', to: 'projects#destroy', as: 'destroy_project'
  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
validates :name, presence: true
validates :description, presence: true
validates :status, presence: true

enum status: [:proposal, :progress, :finished]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :new
  def index
    @projects = Project.all 
    if params[:status] and params[:status] != 'all'
      @projects = @projects.where(status: params[:status])
    end
  end

  def new 
  @project = Project.new 
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to dashboard_path
    end
  end

  private
  #strong params
  def project_params
    params.require(:project).permit(:name, :description, :started_at, :ended_at, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Link Boostrap-Css-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class= "container">
    <%= yield %>
  </div>  
  </body>
</html>

app/views/projects/index.html.erb
<h2>Lista de proyectos</h2>

<%= link_to 'Crear nuevo proyecto', projects_new_path %>

<%= form_with url: "/dashboard", method: :get, class: "form-inline" do |form| %>
  <div class="form-group mx-sm-3 mb-2">
   <%= form.label :query, "Filtrar proyectos: " %>
    <%= form.select :status, [["Todos", :all],["Propuesta", :proposal], ["Progreso", :progress], ["Terminado", :finished]], selected: params[:status], class:'form-control' %>
    </div>
   <%= form.submit "Buscar", class: 'btn btn-success mb-2' %>
 <% end %>
 <br>


<table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Descripción</th>
      <th scope="col">Comenzado</th>
      <th scope="col">Terminado</th>
      <th scope="col">Estado</th>
      <th scope="col">Eliminar</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @projects.each do |project|%>
      <th><%= project.name %></th>
      <td><%= project.description %></td>
      <td><%= project.started_at %></td>
      <td><%= project.ended_at %></td>
      <td><%= project.status %></td>
      <td><%= link_to 'Eliminar', destroy_project_path(project), method: :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h2 class= 'text-center'>Formulario de proyectos</h2>

<% if @project.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@project.errors.count, "error") %> prohibited this
                post from being saved:</h2>
                <ul>
                <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
<%= form_with model: @project do |form| %>
  <%= form.text_field :name, class:'form-control', placeholder: 'Nombre' %>
  <br>
  <%= form.text_area :description, size: "60x10",class:'form-control', placeholder: 'Descripción' %>
  <br>
  <%= form.date_field :started_at, class:'form-control' %>
  <%= form.date_field :ended_at, class:'form-control' %>
  <%= form.select :status, [["Propuesta", :proposal], ["En progreso", :progress], ["Terminado", :finished]],{}, class:'form-control' %>
  <br>
  <%= form.submit 'Enviar', class: 'btn btn-danger' %>
<% end %>

